name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2


    - name: Increment patch version
      run: |
        # Check for changes compared to the previous commit
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "No changes detected."
          exit 0
        fi
        
        # Extract the current version without the -SNAPSHOT suffix from pom.xml
        CURRENT_VERSION=$(grep "<version>.*-SNAPSHOT</version>" pom.xml | head -1 | awk -F'[-><]' '{print $3}')
        echo "Current Version: $CURRENT_VERSION"
        
        # Increment the patch version
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)"-SNAPSHOT"
        echo "New Version: $NEW_VERSION"
        
        # Update pom.xml with the new version
        sed -i "s/<version>$CURRENT_VERSION-SNAPSHOT<\/version>/<version>$NEW_VERSION<\/version>/" pom.xml

    - name: Commit updated version
      run: |
        # Check for changes compared to the previous commit
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        if [[ -z "$CHANGED_FILES" ]]; then
          echo "No changes to commit."
          exit 0
        fi
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Increment patch version to $NEW_VERSION"
        git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
 

